name: test

on:
  push:
    branches:
    - trunk
    paths-ignore:
    - "COPYRIGHT"
    - "LICENSE-*"
    - "**.md"
    - "**.txt"
  pull_request:
    branches:
    - trunk
    paths-ignore:
    - "COPYRIGHT"
    - "LICENSE-*"
    - "**.md"
    - "**.txt"


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: eifinger/setup-rye@v4
      id: setup-rye
    - name: Setup dependencies
      run: rye sync --no-lock
    - name: Run pytest
      run: rye run pytest
