name: test

on:
  push:
    branches:
    - trunk
    paths-ignore:
    - "COPYRIGHT"
    - "LICENSE-*"
    - "**.md"
    - "**.txt"
  pull_request:
    branches:
    - trunk
    paths-ignore:
    - "COPYRIGHT"
    - "LICENSE-*"
    - "**.md"
    - "**.txt"


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup rye
      run: curl -LsSf https://astral.sh/ruff/install.sh | sh
    - name: Setup dependencies
      run: rye sync
    - name: Run pytest
      run: rye run pytest
